jobboard/jobboard/urls.py
from django.contrib import admin
from django.urls import path, include
from orgs import views
from django.conf import settings

# noinspection PyInterpreter
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orgs.urls')),
]

jobboard/orgs/urls.py
from django.urls import path, include
from . import views

#path('', views.IndexView.as_view(), name='index'),
#path('register/', views.UserFormView.as_view(), name='register'),

app_name = 'orgs'

urlpatterns = [

    path('', views.index, name='index'),

    path('login/', views.user_login, name="login"),

    path('prueba/', views.user_login1, name="index1"),

    path('logout/', views.logout, name='logout'),

    path('solicitud/<int:id_vacante>/', views.enviar_solicitud, name='solicitud'),

    path('organizacion/', views.organizacion, name='organizacion'),

    path('organizacion/informacion', views.informacionOrganizacion, name='organinfo'),

    path('organizacion/password/', views.passwordChange, name='orgspassword'),

    path('estudiante/', views.estudiante, name='estudiante'),

    path('organizacion/vacante_view' , views.vacante_view, name='vacanteview'),

    path('organizacion/vacante_details/<int:pk>' , views.vacante_details.as_view, name='vacantedetails'),

    path('organizacion/<int:id_vacante>/delete/', views.vacante_delete, name='vacantedelete'),

    path('estudiante/informacionvacante', views.vacante_edit, name='vacanteinfo'),

    path('estudiante/password/', views.passwordChange, name='orgspassword'),

    path('estudiante/<int:id_vacante>/', views.solicitud_delete, name='solicituddelete'),

    path('estudiante/informacion', views.informacionEstudiante, name='estudinfo'),

    path('estudiante/desactivar/', views.cuenta_desactivar, name='desactivar'),

    path('organizacion/desactivar/', views.cuenta_desactivar, name='desactivar'),
    path('i18n/', include('django.conf.urls.i18n')),
]

jobboard/orgs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Organizacion(User):
    org_descripcion = models.CharField(max_length=255, verbose_name="Descripción")
    org_siglas = models.CharField(max_length=255, verbose_name="Siglas")
    org_figuralegal = models.CharField(max_length=255, verbose_name="Figura legal")
    org_rfc = models.CharField(max_length=255, verbose_name="RFC")
    org_cluni = models.CharField(max_length=255, verbose_name="CLUNI")
    org_webpg = models.CharField(max_length=255, verbose_name="Página web")
    org_objetivo = models.CharField(max_length=255, verbose_name="Objetivo")
    org_campoaccion = models.CharField(max_length=255, verbose_name="Campo acción")
    org_numvacantes = models.IntegerField(verbose_name="Número de vacantes totales", default=0)  # campo que no llena el usuario en el registro
    org_anios = models.CharField(max_length=255, verbose_name="Años de operación")
    org_persona_dpto = models.CharField(max_length=255, verbose_name="Departamento")

    class Meta:
        verbose_name="organización"
        verbose_name_plural="organizaciones"

class Estudiante(User):
    #username
    #email
    #password
    #first_name
    #last_name
    CHOICES_ESCOLARIDAD = (
        ('SECUNDARIA', 'Secundaria'),
        ('PREPARATORIA', 'Preparatoria'),
        ('UNIVERSIDAD', 'Universidad')
    )
    est_fecha_nacimiento = models.DateField(verbose_name="Fecha de nacimiento")
    est_escolaridad = models.CharField(max_length = 255, verbose_name="Escolaridad")
    est_ciudad = models.CharField(max_length=255, verbose_name="Ciudad")
    est_estado = models.CharField(max_length=255, verbose_name="Estado")
    est_horasAcreditadas = models.IntegerField(default='0', verbose_name="Horas acreditadas")
    class Meta:
        verbose_name="Estudiante"

class Domicilio(models.Model):
    exterior = models.CharField(max_length=10)
    interior = models.CharField(max_length=10)
    calle = models.CharField(max_length=45)
    colonia = models.CharField(max_length=45)
    cp = models.CharField(max_length=5)
    longitud = models.DecimalField(max_digits=30, decimal_places=15)
    latitud = models.DecimalField(max_digits=30, decimal_places=15)

    def __str__(self):
        return self.calle + ' ' + self.interior

class Vacante(models.Model):
    TIPO_VACANTE = (
        ('S', 'Servicio social/ voluntariado'),
        ('P', 'Práctica profesionales',)
    )
    HORARIO_VACANTE = (
        ('COMPLETO', 'Tiempo completo'),
        ('MEDIO', 'Medio tiempo'),
        ('FLEXIBLE', 'Horario flexible'),
    )
    AREAS_VACANTE = (
        ('ARQIOTECTURA', 'Arquitectura'),
        ('FINANZAS', 'Finanzas'),
        ('ARTE', 'Arte'),
        ('HUMANIDADES', 'Humanidades')
    )
    APOYO_VACANTE = (
        ('TRANSPORTE', 'Transporte'),
        ('ALIMENTOS', 'Alimentos'),
        ('BECA', 'Beca'),
    )

    tipo = models.CharField(choices=TIPO_VACANTE, max_length=255)
    titulo = models.CharField(max_length=255)
    #posiciones_disponibles = models.PositiveSmallIntegerField(max_length=255)
    descripcion = models.CharField(max_length=255)
    departamento = models.CharField(max_length=255)
    duracion = models.CharField(max_length=255)
    horario = models.CharField(choices=HORARIO_VACANTE, max_length=255)
    areas = models.CharField(choices= AREAS_VACANTE, max_length=255)
    apoyo = models.CharField(choices= APOYO_VACANTE, max_length=255)
    localizacion = models.ForeignKey(Domicilio, on_delete=models.CASCADE, null=True)
    org_vacante = models.ForeignKey(Organizacion, on_delete=models.CASCADE, null=False)

    def get_absolute_url(self):
        return reverse('orgs:organizacion',kwargs={'pk':self.pk})


    def __str__(self):
        return self.titulo + ' - ' + self.descripcion

class Moderador(User):
    class Meta:
        verbose_name="Moderador"
        verbose_name_plural="Moderadores"


 #TABLAS N-N

class vacante_estudiante(models.Model):
    vacante = models.ForeignKey(Vacante, on_delete=models.CASCADE, null=False)
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE, null=False)
    estado = models.CharField(max_length=20)

    def getVacante(self):
        return Vacante.objects.get(id=self.vacante.id)

    def getEstudiante(self):
        return Estudiante.objects.get(user_ptr_id=self.estudiante.id)


#evaluador_evaluado
class organizacion_estudiante(models.Model):
    evaluador = models.ForeignKey(Organizacion, on_delete=models.CASCADE, null=False)
    evaluado = models.ForeignKey(Estudiante, on_delete=models.CASCADE, null=False)
    empatia = models.IntegerField(verbose_name="Empatía")
    puntualidad = models.IntegerField(verbose_name="Puntualidad")
    companierismo = models.IntegerField(verbose_name="Compañerismo")
    responsabilidad = models.IntegerField(verbose_name="Responsabilidad")
    adaptacion = models.IntegerField(verbose_name="Adaptación al cambio")
    proactividad = models.IntegerField(verbose_name="Proactividad")
    actitud = models.IntegerField(verbose_name="Actitud")

jobboard/orgs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as django_logout
from django.contrib.auth.models import User, Group
from .forms import LoginForm, RegistroOrganizacion, SignupEstudiante, RegistroVacante,PasswordChange, RegistroDomicilio
from django.views.generic.detail import DetailView
from django.http import HttpResponse
from .models import Vacante, Organizacion, Estudiante, vacante_estudiante, organizacion_estudiante


def user_login1(request):
    return render(request, 'orgs/index1.html')


def index(request):

    try:
        orgs = Organizacion.objects.get(user_ptr_id=request.session['_auth_user_id'])
    except (KeyError, Organizacion.DoesNotExist):
        orgs = 0
    try:
        student = Estudiante.objects.get(user_ptr_id=request.session['_auth_user_id'])
    except (KeyError, Estudiante.DoesNotExist):
        student = 0

    vacante = Vacante.objects.all()
    if(request.method)=='POST':
        form_registro = RegistroOrganizacion(request.POST)

        if form_registro.is_valid():
            form_registro.save()
            cd = form_registro.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password1'])
            user_group = User.objects.get(id=user.id)
            group = Group.objects.get(name='Organizacion')
            group.user_set.add(user_group)
            #org_nombre = form.cleaned_data.get('org_nombre')
            username = form_registro.cleaned_data.get('username')
            password1 = form_registro.cleaned_data.get('password1')
            login(request, user)
            return redirect('orgs:organizacion')
        else:
            form_login = LoginForm(request.POST)

            if form_login.is_valid():
                cd = form_login.cleaned_data
                user = authenticate(username=cd['username'], password=cd['password'])
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        return render(request, 'orgs/organizacion.html')
                    else:
                        return HttpResponse('User is not active')
            else:
                form_registro_estudiante = SignupEstudiante(request.POST)
                print(form_registro_estudiante.is_valid())
                if form_registro_estudiante.is_valid():
                    form_registro_estudiante.save()

                    cd = form_registro_estudiante.cleaned_data
                    user = authenticate(username=cd['username'], password=cd['password1'])
                    user_group = User.objects.get(id=user.id)
                    group = Group.objects.get(name='Estudiante')
                    group.user_set.add(user_group)
                    login(request, user)
                    return redirect('orgs:estudiante')
    else:
        form_registro = RegistroOrganizacion()
        form_login = LoginForm()
        form_registro_estudiante = SignupEstudiante()
    return render(request, 'orgs/index.html', {'vacantes': vacante,'form_registro':form_registro, 'form_login':form_login, 'form_registro_estudiante':form_registro_estudiante, 'orgs': orgs, 'student': student})


def user_login(request):
    if request.method == 'POST':
        form_login = LoginForm(request.POST)
        if form_login.is_valid():
            cd = form_login.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                user_group = User.objects.get(id=user.id)
                if user.is_active:
                    login(request, user)
                    #org_group = Group.objects.filter(name='Organizacion')
                    if user_group.groups.filter(name='Organizacion').exists():
                        return redirect('orgs:organizacion')
                    elif user_group.groups.filter(name='Estudiante').exists():
                        return redirect('orgs:estudiante')
                else:
                    return HttpResponse('User is not active')
            else:
                return redirect('orgs:index')
        else:
            return HttpResponse('form is not valid')
    else:
        form_registro = RegistroOrganizacion()
        form_login = LoginForm()
        return render(request, 'orgs/sign_up.html', {'form_registro': form_registro, 'form': form_login})


def organizacion(request):
    orgs = Organizacion.objects.get(user_ptr_id=request.session['_auth_user_id'])
    vacantes = orgs.vacante_set.all()
    lista = Vacante.objects.all()
    form = RegistroVacante()
    formpass = PasswordChange()
    return render(request, 'orgs/organizacion.html',{'vacantes': vacantes, 'form': form, 'formpass': formpass, 'session': request.session['_auth_user_id'], 'orgs': orgs , 'lista': lista})


def informacionOrganizacion(request):
    organizacion = Organizacion.objects.get(user_ptr_id=request.session['_auth_user_id'])
    organizacion.org_descripcion = request.POST['descripcion']
    organizacion.org_siglas = request.POST['siglas']
    organizacion.org_figuralegal = request.POST['figuralegal']
    organizacion.org_rfc = request.POST['rfc']
    organizacion.org_cluni = request.POST['cluni']
    organizacion.org_webpg = request.POST['webpage']
    organizacion.org_objetivo = request.POST['objetivo']
    organizacion.org_campoaccion = request.POST['campodeaccion']
    organizacion.org_anios = request.POST['anios']
    organizacion.save()
    return redirect('orgs:organizacion')


def passwordChange(request):
    if request.method == 'POST':
        form = PasswordChange(request.POST)
        if form.is_valid():
            user = User.objects.get(id=request.session['_auth_user_id'])
            #user = get_object_or_404(User, id=request.session['_auth_user_id'])
            oldpass = form['oldpassword'].value()
            cd = form.cleaned_data
            user_test = authenticate(username=user.username, password=oldpass)
            newpass1 = form['newpassword1'].value()
            newpass2 = form['newpassword2'].value()
            if user_test is not None and newpass1 == newpass2:
                user.set_password(newpass1)
                user.save()
            user_group = User.objects.get(id=user.id)
            if user_group.groups.filter(name='Organizacion').exists():
                return redirect('orgs:organizacion')
            elif user_group.groups.filter(name='Estudiante').exists():
                return redirect('orgs:estudiante')
    else:
        #  PENDIENTE TERMINAR ESTA PARTE -----
        return redirect('orgs:organizacion')


def logout(request):
    django_logout(request)  #EL LOGOUT HACE EL FLUSH DE LA SESSION DE FORMA AUTOMATICA
    return redirect('orgs:index')


def estudiante(request):
    formpass = PasswordChange()
    user = Estudiante.objects.get(user_ptr_id=request.session['_auth_user_id'])
    vacantes_estudiante = user.vacante_estudiante_set.all()
    lista = Vacante.objects.all()
    return render(request,'orgs/estudiante.html', {'formpass': formpass, 'user': user, 'vacantes_estudiante': vacantes_estudiante, 'lista': lista})


def informacionEstudiante(request):
    estudiante = Estudiante.objects.get(user_ptr_id=request.session['_auth_user_id'])
    #estudiante.est_fecha_nacimiento = request.POST['fecha']    PENDIENTE LA PUTA FECHA
    estudiante.est_escolaridad = request.POST['escolaridad']
    estudiante.est_estado = request.POST['estado']
    estudiante.est_ciudad = request.POST['ciudad']
    estudiante.est_horasAcreditadas = request.POST['horas']
    estudiante.save()
    return redirect('orgs:estudiante')


def cuenta_desactivar(request):
    user = User.objects.get(id=request.session['_auth_user_id'])
    user.is_active = 0
    user.save()
    return redirect('orgs:index')


def vacante_view(request):
    if request.method == 'POST':
        form = RegistroVacante(request.POST)
        #domc = Domicilio(exterior=form.exterior, interior=form.interior, calle=form.calle, colonia=form.colonia, cp=form.cp, longitud=form.longitud, latitud=form.latitud)
        #domc = RegistroDomicilio(request.POST, request.FILES)
        if form.is_valid():
            #domc.save()
            vacante = form.save(commit=False)
            orgs = Organizacion.objects.get(user_ptr_id=request.session['_auth_user_id'])
            vacante.org_vacante = orgs
            vacante.save()
        return redirect('orgs:organizacion')
    else:
        #form = RegistroVacante()
        #formpass = PasswordChange()
        return redirect('orgs:organizacion')
        #return render(request, 'orgs/organizacion.html', {'form': form, 'formpass': formpass, 'session': request.session['_auth_user_id']})


class vacante_details(DetailView):
    model = Vacante
    template_name = 'details_vacante.html'


def vacante_edit(request):
    estudiante = Estudiante.objects.get(user_ptr_id=request.session['_auth_user_id'])
    estudiante.est_escolaridad = request.POST['escolaridad']
    estudiante.est_estado = request.POST['estado']
    estudiante.est_ciudad = request.POST['ciudad']
    estudiante.est_horasAcreditadas = request.POST['horas']
    estudiante.save()
    return redirect('orgs:organizacion')


def vacante_delete(request, id_vacante):
    Vacante.objects.get(id=id_vacante).delete()
    return redirect('orgs:organizacion')


def enviar_solicitud(request, id_vacante):
    estudiante = Estudiante.objects.get(user_ptr_id=request.session['_auth_user_id'])
    if not estudiante.vacante_estudiante_set.filter(vacante_id=id_vacante).exists():
        solicitud = vacante_estudiante(estado='pendiente', vacante_id=id_vacante, estudiante_id=request.session['_auth_user_id'])
        solicitud.save()
    return redirect('orgs:estudiante')


def solicitud_delete(request, id_vacante):
    vacante_estudiante.objects.get(id=id_vacante).delete()
    return redirect('orgs:estudiante')

jobboard/orgs/templates/orgs/charts.html
<html>
  <head>
    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

      // Load the Visualization API and the corechart package.
      google.charts.load('current', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Ciudad');
        data.addColumn('number', 'Cantidad de vacantes');
        data.addRows([
          ['CDMX', 44],
          ['Guadalajara', 62],
          ['Ciudad Gótica', 4],
          ['Querétaro', 254],
          ['Fondo de biquini', 255]
        ]);

        // Set chart options
        var options = {'title':'Top 5 ciudades con más vacantes',
                       'width':400,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
  </head>

  <body>
    <!--Div that will hold the pie chart-->
    <div id="chart_div"></div>
  </body>
</html>

jobboard/orgs/templates/orgs/estudiante.html
{% extends 'orgs/base.html' %}

{% block navderecha %}

    <a class="nav-link dropdown-toggle" href="#" id="orgsajustes" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Engrane.jpg</a>
    <div class="dropdown-menu" aria-labelledby="orgsajustes">
        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#modalInformacion" >Perfil</a>
        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#modalcontraseña">Cambiar Contraseña</a>
        <a class="dropdown-item" href="{% url 'orgs:logout' %}">Desconectar</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#modaldesactivar">Desactivar cuenta</a>
    </div>

{% endblock %}

{% block body %}

    <h5>Felicidades, eres un estudiante</h5>



<!--TABLA CON LISTA DE SOLICITUDES ENVIADAS POR EL ESTUDIANTE -->

    <h1>Datos</h1>
    <table class="table table-bordered display DataTables">
        <thead>
            <tr>
                <td>Titulo</td>
                <td>Estado</td>
                <td>Acciones</td>
            </tr>
        </thead>
        <tbody>
            {% if vacantes_estudiante %}
                {% for vacante_est in vacantes_estudiante %}
                    <tr>
                        <td>{{ vacante_est.getVacante.titulo }}</td>
                        <td class="text-warning">{{ vacante_est.estado }}</td>
                        <td>
                            <button class="btn btn-primary" data-toggle="modal" data-target="#modaldetail{{ vacante_est.id }}">Ver Detalles</button>
                            <button class="btn btn-danger text-white" data-toggle="modal" data-target="#modaldelete{{ vacante_est.id }}">Eliminar</button>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <h5>No tiene solicitudes de vacantes aún</h5>
            {% endif %}
        </tbody>
    </table>

<!-- TERMINA TABLA CON LISTA DE SOLICITUDES ENVIADAS POR EL ESTUDIANTE -->

<!-- MODAL CONFIRMAR ELIMINICACIÓN DE SOLICITUD DE VACANTE -->

    {% for vacante_est in vacantes_estudiante %}
        <div class="modal fade" id="modaldelete{{ vacante_est.id }}" tabindex="-1" role="dialog" aria-labelledby="modaldelete" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                     <h5 class="modal-title" id="exampleModalLongTitle">Eliminar Solicitud</h5>
                     <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                         <span aria-hidden="true">&times;</span>
                     </button>
              </div>
                <div class="modal-body">
                    <div class="container">
                        <h5>¿Estás seguro que deseas eliminar la solicitud?</h5>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <a class="btn btn-danger text-white" href="{% url 'orgs:solicituddelete' vacante_est.id %}">Eliminar</a>
                    </div>
                </div>
            </div>
          </div>
        </div>
    {% endfor %}

<!-- TERMINA MODAL CONFIRMAR ELIMINICACIÓN DE SOLICITUD DE VACANTE -->

<!-- MODAL CAMBIAR CONTRASEÑA -->

<div class="modal fade" id="modalcontraseña" tabindex="-1" role="dialog" aria-labelledby="cambiarContraseña" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
             <h5 class="modal-title" id="exampleModalLongTitle">Cambiar Contraseña</h5>
             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                 <span aria-hidden="true">&times;</span>
             </button>
      </div>
        <div class="modal-body">
            <div class="container">
                <form method="post" action="{% url 'orgs:orgspassword' %}">
                 {% csrf_token %}
                {%  for field in formpass %}
                    <div class="form-group row">
      <div class="col-sm-4">
          <label for="{{field.name}}" class="col-form-label">{{ field.label_tag }}</label>
      </div>
          <div class="col-sm-8">
            {{ field }}
            <br>
            <small id="help{{ field.auto_id }}" class="text-danger"></small>
          {% if field.help_text %}
            <small class="right" style="color: grey">{{ field.help_text }}</small>
          {% endif %}

        </div>

        </p>
      </div>
                    {% endfor %}
                <div class="row justify-content-end">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <button class="btn btn-primary" type="submit">Guardar Cambios</button>
          </div>
                 </form>
            </div>
        </div>
    </div>
  </div>
</div>

<!-- TERMINA MODAL CAMBIAR CONTRASEÑA -->

<!-- MODAL CAMBIAR INFORMACIÓN PERSONAL -->

<div class="modal fade" id="modalInformacion" tabindex="-1" role="dialog" aria-labelledby="cambiarContraseña" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
             <h5 class="modal-title" id="exampleModalLongTitle">Información Personal</h5>
             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                 <span aria-hidden="true">&times;</span>
             </button>
        </div>
        <div class="modal-body">
            <div class="container">
                <form method="post" action="{% url 'orgs:estudinfo' %}">
                 {% csrf_token %}
                    <div class="form-group">
                        <label for="fecha">Fecha de Nacimiento</label><br>
                        <input name="fecha" type="text" value="{{ user.est_fecha_nacimiento }}" required>
                    </div>
                    <div class="form-group">
                        <label for="escolaridad">Grado de Escolaridad</label><br>
                        <input name="escolaridad" type="text" value="{{ user.est_escolaridad }}" required>
                    </div>
                    <div class="form-group">
                        <label for="estado">Estado</label><br>
                        <input name="estado" type="text" value="{{ user.est_estado }}" required>
                    </div>
                    <div class="form-group">
                        <label for="ciudad">Ciudad</label><br>
                        <input name="ciudad" type="text" value="{{ user.est_ciudad }}" required>
                    </div>
                    <div class="form-group">
                        <label for="horas">Grado de Escolaridad</label><br>
                        <input name="horas" type="text" value="{{ user.est_horasAcreditadas }}" required>
                    </div>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button class="btn btn-primary" type="submit">Guardar Cambios</button>
                </form>
            </div>
        </div>
    </div>
  </div>
</div>

<!-- TERMINA MODAL CAMBIAR INFORMACIÓN PERSONAL -->

<!-- COMIENZA MODAL DESACTIVAR CUENTA -->

<div class="modal fade" id="modaldesactivar" tabindex="-1" role="dialog" aria-labelledby="cambiarContraseña" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
             <h5 class="modal-title" id="exampleModalLongTitle">Confirmar Desactivar Cuenta</h5>
             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                 <span aria-hidden="true">&times;</span>
             </button>
      </div>
        <div class="modal-body">
            <div class="container">
                    <p>¿Estás seguro que deseas desactivar tu cuenta?</p>
                    <p>No podrás tener acceso a tu cuenta. En caso de querer que se reactive tendrás que enviar un correo al soporte</p>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <a class="btn btn-primary" href="{% url 'orgs:desactivar' %}">Confirmar</a>
            </div>
        </div>
        </div>
    </div>
  </div>
</div>

<!-- TERMINA MODAL DESACTIVAR CUENTA -->



    <script>
        function password(){
            pass1 = document.getElementById('pass1');
            pass2 = document.getElementById('pass2');
            helppass1 = document.getElementById('helpid_newpassword1');
            helppass2 = document.getElementById('helpid_newpassword2');
            console.log(helppass1);
            if(pass1.value.length < 7){
                helppass1.innerHTML = 'La contraseña debe tener al menos 7 caracteres';
            }
            else{
                helppass1.innerHTML = '';
            }
        }
    </script>
{% endblock %}

jobboard/orgs/templates/orgs/sign_up.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block seo_title %}{% endblock %}</title>
        <meta name="description" content="{% block seo_description %}{% endblock %}">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    </head>

    <body>
    {% block content %}
      <h2>Sign up</h2>
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
          <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
        {% endfor %}
        <button type="submit">Sign up</button>
      </form>
    {% endblock %}
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>